// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVyccuh7S2BwawEJ79xWFJdZ_yzramiL8',
    appId: '1:442357295564:web:150bdc7ba55450ac0d5569',
    messagingSenderId: '442357295564',
    projectId: 'flutter-meditations',
    authDomain: 'flutter-meditations.firebaseapp.com',
    storageBucket: 'flutter-meditations.appspot.com',
    measurementId: 'G-1CS9XZ16TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk7Y-432MXmi8YOoTMj5w6YYjQVVTMRWo',
    appId: '1:442357295564:android:2ce923b56170c8870d5569',
    messagingSenderId: '442357295564',
    projectId: 'flutter-meditations',
    storageBucket: 'flutter-meditations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqHMwSvUj7B3nwKTQs6Sd5pRJ0PvMPAUA',
    appId: '1:442357295564:ios:1dc6c3c5cec23b0e0d5569',
    messagingSenderId: '442357295564',
    projectId: 'flutter-meditations',
    storageBucket: 'flutter-meditations.appspot.com',
    iosClientId: '442357295564-p8boqk3anihmlebi5ai34j7uo9u2fiqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditations',
  );
}
